# Site settings
title: Open Source Smart Watch
short-title: OSSW
email: ossw@althink.com
url: https://ossw.github.io
description: "Open Source Sport Watch"

collections:
  instructions:
    output: true

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Krzysztof Szczesniak

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
#highlighter: rouge